#!/bin/bash

set -e

echo "[R-SNORT] postinst ejecutado..."

if [ ! -d /opt/r-snort ]; then
  echo "[R-SNORT] ERROR: /opt/r-snort no existe. Instalación corrupta."
  exit 1
fi

chmod +x /opt/r-snort/*.sh /opt/r-snort/bin/*.sh

echo "[R-SNORT] Saltando ejecución automática: el instalador externo se encarga."

echo "[R-SNORT] postinst completado correctamente."
